# Generated by Django 4.2.1 on 2023-06-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('payment_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Платеж')),
                ('payment_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('status', models.CharField(max_length=15, verbose_name='Статус платежа')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutModel',
            fields=[
                ('payout_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Выплата')),
                ('payout_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма выплаты')),
                ('payout_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выплаты')),
                ('status', models.CharField(verbose_name='Статус выплаты')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
