# Generated by Django 4.2.1 on 2023-06-29 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('count_donations', models.IntegerField(default=0, verbose_name='Количество донатов')),
                ('goal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='DonateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Псевдоним')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение доната')),
                ('withdrawn', models.BooleanField(default=False, verbose_name='Выведено')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmodel')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamer', to='users.streamermodel')),
            ],
        ),
    ]
