# Generated by Django 4.2.1 on 2023-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamermodel',
            name='avatar',
            field=models.ImageField(default='./static/pictures/avatar-example.jpg', upload_to='', verbose_name='Аватарка'),
        ),
    ]
