# Generated by Django 4.2.1 on 2023-07-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_streamermodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payout', models.CharField(choices=[('ЮMoney', 'ЮMoney'), ('Банковская карта', 'Банковская карта'), ('СБП', 'СБП')], max_length=16, verbose_name='Способ вывода')),
                ('number_card', models.DecimalField(decimal_places=0, max_digits=20, unique=True, verbose_name='Номер карты')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streamerCard', to='users.streamermodel', verbose_name='Стример')),
            ],
        ),
    ]
