# Generated by Django 4.2.1 on 2023-07-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_streamercard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamermodel',
            name='goal',
        ),
        migrations.AlterField(
            model_name='streamercard',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamerCard', to='users.streamermodel', verbose_name='Стример'),
        ),
        migrations.AlterField(
            model_name='streamermodel',
            name='avatar',
            field=models.ImageField(default='default_profile_picture.png', upload_to='', verbose_name='Аватарка'),
        ),
        migrations.CreateModel(
            name='StreamerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цель')),
                ('min_sum_donate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма доната')),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.streamermodel')),
            ],
        ),
    ]
