# Generated by Django 4.2.1 on 2023-07-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_streamermodel_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamersettings',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streamerSettings', to='users.streamermodel', verbose_name='Стример'),
        ),
    ]
