# Generated by Django 4.2.1 on 2023-07-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_streamersettings_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamersettings',
            name='sum_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма цели'),
        ),
    ]
