# Generated by Django 4.2.1 on 2023-07-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0007_streamercard_default_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemodel',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='donate', to='payments.paymentmodel'),
        ),
    ]
