# Generated by Django 4.2.1 on 2023-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_donatemodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamercard',
            name='default_payout',
            field=models.BooleanField(default=False, verbose_name='Выбранный способ вывода'),
        ),
    ]
