# Generated by Django 4.2.1 on 2023-07-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_streamercard_default_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamersettings',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='streamersettings',
            name='sum_goal',
        ),
        migrations.CreateModel(
            name='StreamerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма цели')),
                ('goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цель')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streamerGoal', to='users.streamermodel', verbose_name='Стример')),
            ],
        ),
    ]
