# Generated by Django 4.2.1 on 2023-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_streamersettings_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamergoal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
