# Generated by Django 4.2.1 on 2023-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_streamergoal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamersettings',
            name='min_sum_donate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Минимальная сумма доната'),
        ),
    ]
